### ISSUE TITLE
Hello @geberit

### ISSUE THREAD

**Issue by ypid** [ypid/geberit_github_account#1]
Hi user @geberit

I wanted to ask you if you could maybe pass the account @geberit over to me? To do this, I guess it would be the easiest to delete the account so that I could open an organization https://github.com/geberit.

Disclaimer: I am an employee of [Geberit Verwaltungs GmbH](http://www.geberit.de/de_de/head_structure/unternehmen/geberit/geberit_verwaltungs_gmbh.html) and it would be nice if the account could be used for FLOSS projects developed at Geberit.

**Comment by ypid-geberit** [comment]
~~https://github.com/geberit-com~~ exists now because of unresponsiveness of @geberit but waiting for response from GitHub because @geberit seems to violate the [Name Squatting Policy](https://help.github.com/articles/name-squatting-policy/) because it never had any activity. ~~https://github.com/geberit-com is registered as backup/fallback for now~~.

**Comment by ypid-geberit** [comment]
https://github.com/geberit is now owned by [Geberit](https://www.geberit.com/en/) and will be used as intended (Free and open-source software developed at/for Geberit). Thanks very much to the GitHub support team :)

**Comment by ypid** [comment]
Apparently, GitHub has renamed the account to https://github.com/geberit-zz which I saw because I followed the account and this relationship survived the renaming.
